### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by kbatchelli** [gc2023/SuperAnticheat#1]
# Console Error
# Provide error messages here:

# When the bug occurrs? Climbing
# Describe when the bug occurrs: When I climb a ladder it would say I was using some hack.

# Server Version: spigot 1.13.2, latest
# Anticheat Version:1.0.8
# ProtocolLib Version: latest
# Is the config file the newest?: yes

**Comment by gc2023** [comment]
Working on it now! Thanks for your report!

**Comment by gc2023** [comment]
All fixed!

**Comment by kbatchelli** [comment]
thanks

**Comment by kbatchelli** [comment]
thanks
