### ISSUE TITLE
Speed Bypass

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#19]
Hack Client: Ramen 
Hacking Type: SolentSpeed
Anticheat Version: Latest
Server Version: 1.8

Videos: https://streamable.com/sz6u0

Heres the source code to the speed https://ghostbin.com/paste/3nxgx

**Comment by gc2023** [comment]
Interesting. Thanks for giving source to that havk because It makes it easier for me to patch.

**Comment by coolpvpv** [comment]
I kinda feel like the fly or speed check is solent cause my solentfly also works I will report the fly later

**Comment by gc2023** [comment]
Hi, please link me this Ramen Hacked Client, for i cannot find it online and I need it for testing to patch the bypass.
