### ISSUE TITLE
groundspoof false flag and noslowdown false flag

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#2]
Videos: https://streamable.com/46z76

Anticheat Version: latest
Server Version: 1.8.8
ProtocolLib Version: 3.6.4 (going to try on latest ProtocolLib after this report)

**Comment by gc2023** [comment]
Looking into it now! Sorry for the delay!

**Comment by gc2023** [comment]
Actually, I am unable to re-cause that noslowdown false positive on my 1.8.8 server. I see that you have other hacks on like HeadRotations and stuff. Try turning off Every hack and doing the block run thing.

**Comment by gc2023** [comment]
Nvm i was able to recreate the NoSlowdown false positive. Fixing now.

**Comment by gc2023** [comment]
Still working on fixing groundspoof false positive. Just wanted to let you know.

**Comment by gc2023** [comment]
All fixed!

**Comment by coolpvpv** [comment]
ok
