### ISSUE TITLE
Fly Bypass

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#20]
Hack Client: Ramen
Hacking Type: SolentFly
Anticheat Version: Latest
Server Version: 1.8

Videos: https://streamable.com/3e4tv

Heres the source code to the fly https://ghostbin.com/paste/myjqr

**Comment by gc2023** [comment]
Thank you for this report. Remember i am on vacation and will be back on april 5th, so thats when i will get to work on all of this :)
