### ISSUE TITLE
Antikb False Flag

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#21]
Videos: https://streamable.com/echnf

Anticheat Version: Latest
Server Version: 1.8.8
ProtocolLib Version: Latest

and heres a download to a good anticheat test map https://www.mediafire.com/file/db6plp3fwtdew70/Anticheat_Test_Map.rar/file

**Comment by gc2023** [comment]
Thank you for the map! Fixed next update
