### ISSUE TITLE
Glide False Flag

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#22]
Videos: https://streamable.com/yya97

Anticheat Version: Latest
Server Version: 1.8.8 
ProtocolLib Version: Latest

**Comment by gc2023** [comment]
Interesting. I was able to walk up snow like that a few versions ago. Ill look intot his as the cirrent glide check really doesnt detect anything and im improving for the next update.

**Comment by coolpvpv** [comment]
well i was walking on the edge of the block

**Comment by gc2023** [comment]
Ill look into it when im get back.
