### ISSUE TITLE
Airjump Bypass

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#64]
Hack Client: Flux b13 here is the download http://www.mediafire.com/file/00s515prnfe81pq/Flux_B13.rar/file
Hacking Type: Airjump
Anticheat Version: Latest
Server Version: 1.8.8

Videos: https://streamable.com/4kbo7

**Comment by gc2023** [comment]
I am unable to bypass using Flux b13 with AirJump.

**Comment by gc2023** [comment]
Nevermind, I was able to somewhat bypass it. Fixed next update.
