### ISSUE TITLE
Error while use PlayerMoveEvent

### ISSUE THREAD

**Issue by klzxc99** [gc2023/SuperAnticheat#65]
# Console Error
# Provide error messages here:

07.04 06:12:18 [Server] ERROR Could not pass event PlayerMoveEvent to SuperAC v1.1.0
07.04 06:12:18 [Server] INFO org.bukkit.event.EventException: null
07.04 06:12:18 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:436) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:590) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:10) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
07.04 06:12:18 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
07.04 06:12:18 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:598) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:198) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:548) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:457) ~[custom.jar:git-Paper-latest]
07.04 06:12:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
07.04 06:12:18 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 41, Size: 40
07.04 06:12:18 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_161]
07.04 06:12:18 [Server] INFO at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_161]
07.04 06:12:18 [Server] INFO at main.c.c.c.a(FastSneak.java:31) ~[?:?]
07.04 06:12:18 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor289.execute(Unknown Source) ~[?:?]
07.04 06:12:18 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[custom.jar:git-Paper-latest]

# When the bug occurrs?
# Describe when the bug occurrs: 

Error while using PlayerMoveEvent

# Server Version: 1.12.2
# Anticheat Version: 1.1.0
# ProtocolLib Version: 4.4.0-b425
# Is the config file the newest?: yes

**Comment by gc2023** [comment]
It looks like you are trying to use Paper-Spigot, which is not supported. Try with Spigot 1.12.2
