### ISSUE TITLE
WaterWalk (A) False Flag

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#67]
How you trigger the false positive

Get 15 ice get two stone and a water bucket place all the ice at the end put the two stone up place water bucket get rid of the stone block then run and jump on the top of the water then it falses WaterWalk (A)

Videos: https://streamable.com/kag3u

Anticheat Version: Latest
Server Version: 1.8.8
ProtocolLib Version: Latest

**Comment by gc2023** [comment]
Interesting. I will look into this.
