### ISSUE TITLE
Speed (B) False Flag

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#68]
How you trigger the false positive

get 15 ice get 4 blocks of stone place one at the end of it then a second over the last one then another up run and jump on the ice and when you get to the end get on the stone and it will false Speed (B)

Videos: https://streamable.com/3ph6j

Anticheat Version: Latest
Server Version: 1.8.8
ProtocolLib Version: Latest

**Comment by gc2023** [comment]
Yeah I discovered this too. It checks to see if your on ice and then to not detect you but when you are jumping off the ice at that ice speed it sees that you are no longer on ice and still moving at the ice speed and flags you. Fixing for next update.
