### ISSUE TITLE
minecart cobweb glitch

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#76]
if you ride in a minecart under cobwebs it will kick you out of the minecart

Server Version: 1.8.8
Anticheat Version: Latest
ProtocolLib Version: Latest
Is the config file the newest?: yes

**Comment by gc2023** [comment]
Fixed next update.

**Comment by gc2023** [comment]
Actually, this is a bug with minecraft. I removed my ac, and it still occurred. This is minecraft, not my ac.
