### ISSUE TITLE
Criticals Bypass

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#84]
Hack Client: Remix
Hacking Type: Criticals mode singlepacket
Anticheat Version: Latest
Server Version: 1.8.8

download to client http://www.mediafire.com/file/hugqd77i2rgqdun/Remix_1.3.rar/file

**Comment by gc2023** [comment]
That does not work, When you critical on someone, if you do not see the particles, you did not critical. This critical does not show me criticaling and does not deal the critical damage. Thus this being not a bypass.

**Comment by coolpvpv** [comment]
i had animations off

**Comment by gc2023** [comment]
I had them on, still no criticals.
