### ISSUE TITLE
Feature Request - Check.yml

### ISSUE THREAD

**Issue by Acenox** [gc2023/SuperAnticheat#86]
# What features would you like added?
# Describe it here:
Hello,
I just installed your plugin, and I find it really not bad, I have a small suggestion on the config:

Speed-a:
enabled: true <- Enabled / Disabled.
silent: false Silent if you do not want to cancel, teleport, e.t.c on flags.
cancel_after_violation: 3 <- After which the hack.
violation_divisor: 2 <- Any notifications will take place when the violations are 2, 4, 6, 8, 10, 12 ...
disabled_worlds: 'hub, creativeWorld, survival, survival_the_end' <- The worlds the check will not run.
silent_worlds: 'ocean, sky, hub' <- The worlds will check work only silently.
max-violations: 10
punishments: <- Start of the punishment section.
'5': <- Punishment that will execute in a certain level violation.
   '1': say {player} is speed hacking! <- First command executed.
   '2': kick {player} Moved too quickly <- Second command executed.

Best regards,

**Comment by gc2023** [comment]
Hello! I do like this config layout and I will add this is a future update, however I will not make a punishments system like that I will modify slightly. Thanks for your request!
