### ISSUE TITLE
Error on Server join and moving

### ISSUE THREAD

**Issue by Clasher31HD** [gc2023/SuperAnticheat#87]
Hi, when i join my server and walking around, my console gets spammed by errors
https://pastebin.com/A5p05Rap

Server: Spigot 1.13.2
AC Version: 1.1.4
Protocollib: version b425

I hope you can fix this Issue

**Comment by gc2023** [comment]
Please make sure you use protocollib off of Spigotmc.org not of jenkins, for those versions are not always stable. If you need to download protocollib, click [here](https://www.spigotmc.org/resources/protocollib.1997/) or goto [https://www.spigotmc.org/resources/protocollib.1997/](https://www.spigotmc.org/resources/protocollib.1997/)

However, I have fixed this bug on my end. However if the error still persists, try using protocollib 4.3.0 or 4.4.0.
