### ISSUE TITLE
Spamming Error on join and move

### ISSUE THREAD

**Issue by Clasher31HD** [gc2023/SuperAnticheat#88]
# Console Error
# Provide error messages here:
https://pastebin.com/S31DPpWd

# When the bug occurrs?
# Describe when the bug occurrs:
when i join the server and walk around

# Server Version: Spigot 1.13.2
# Anticheat Version: 1.1.5
# ProtocolLib Version: 4.4.0
# Is the config file the newest?: (yes/no) yes

You dindn't fix the issue!

**Comment by gc2023** [comment]
Try using 4.3.0 protocollib. If the error is fixed using 4.3.0, let me know and ill fix it with 4.4.0

**Comment by Clasher31HD** [comment]
I've tried it with 4.3.0 protocollib, but still the same error spamming in console

**Comment by gc2023** [comment]
I will look into this issue.
