### ISSUE TITLE
Nofall (B) False Flag

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#89]
How you trigger the false positive
Stand on a powered rail and move and jump around on it and it will false Nofall (B)

Videos: https://streamable.com/z9ng1

Anticheat Version: 1.1.6 or whatever the latest version is
Server Version: 1.8.8
ProtocolLib Version: 4.4.0 or whatever the latest version is

**Comment by gc2023** [comment]
Yes Nofall b is still in development (i know it doesnt say but it is currently).

I will fix this for next update.
