### ISSUE TITLE
Step / Speed False Flag

### ISSUE THREAD

**Issue by coolpvpv** [gc2023/SuperAnticheat#90]
How you trigger the false positive
Place a block then put a slab after it then run up it on the side to better explain watch the video

Videos: https://streamable.com/3843w

Anticheat Version: 1.1.6 or whatever the latest version is
Server Version: 1.8.8
ProtocolLib Version: 4.4.0 or whatever the latest version is

**Comment by gc2023** [comment]
Yes I am still working on step and fixing some falses. Fixed next update.
